- benchmarks/benchmarks.cpp
- benchmarks/tasks/catalan/wast/impl.c
- benchmarks/tasks/fac/wast/impl.c
- benchmarks/tasks/fib/wast/impl.c
- benchmarks/tasks/gcd/wast/impl.c
- benchmarks/tasks/primes/wast/impl.c
- benchmarks/tasks/tak-mem/wast/impl.c
- benchmarks/tasks/tak/wast/impl.c
- instructions.cpp
The buffer underflow caused by a `frame->sp` that is lower than -1 turned out to be a benchmark specific bug.
The `run_benchmarks` function in `benchmarks.cpp` uses the `invoke` function to call the main of each benchmark module.
Compiling the C programs with clang 13.0 results in a Wasm main function expecting three arguments as the main function in C expects an `int `and a `char**` parameter.
The `run_benchmarks` function did not account for this and did not push any parameters on the stack and called the function with 3 parameters anyway, naturally causing a buffer underflow.
**Implemented solution:** Rename the main function in the C implementations to "bench", so we can invoke a "bench" function that takes no parameters in `benchmarks.cpp` rather than a main that expects two …
> Fix issue #21

- src/Debug/debugger.cpp
- src/Debug/debugger.h
- src/Interpreter/instructions.cpp
**Bug:** WARDuino reports a breakpoint was hit with the message: `"AT {program pointer}!"` However, this messages was still printed to `stdout` and not the debugger socket. Subsequently, breakpoints did not work in the plugin with the emulator.
**Fix:** Added a `Debugger::notifyBreakpoint` method.
> Fix breakpoint notification

- src/Debug/debugger.cpp
- src/Debug/debugger.h
- src/Interpreter/instructions.cpp
- src/WARDuino.h
- src/WARDuino/WARDuino.cpp
For now onwards, adding a breakpoint or requesting a wood dump works on virtual addresses rendering thus the `start` value irrelevant. The virtual addresses were not implemented for all interrupts (e.g., `interruptDump`) and this is because most of those interrupts will be removed once [enhancement 127: fine-grained state request and update](https://github.com/TOPLLab/WARDuino/issues/127) is implemented.
> Enhancement/126 Only virtual addresses

- src/Debug/debugger.cpp
- src/Debug/debugger.h
- src/Utils/util.cpp
- src/Utils/util.h
- tests/vm_unit_tests/serialisation_test.cpp
This PR adds to WARDuino the ability to update stack values. Concretely what the PR does:
- refactored the interruptUPDATEGlobal to use deserialiseStackValue
- add unit tests for the deserialiseStackValue
- add interrupt to update StackValue
> Add update stackvalue message

- .github/workflows/compile.yml
- CMakeLists.txt
- library.properties
- src/Edward/proxy_supervisor.cpp
- Restore callbackmapping synchronization for EDWARD
- Use `v5.0.2` in idf compilation action
> Version 0.3.1

- src/Primitives/arduino.cpp
- src/Primitives/emulated.cpp
Add the `analog_write` primitive.
> Analog write primitive

- src/Debug/debugger.cpp
Step over does not work if the current opcode is a call instruction and there is a breakpoint on it. The `handleSTEP` function skips breakpoints but if the current opcode is a call or indirect call instruction we just set a mark and put the vm in running state. If the current pc is a breakpoint the vm never goes any further because it instantly hits the breakpoint.
> Fix step over not stepping if at a breakpoint placed on a call instruction

- platforms/CLI-Emulator/main.cpp
- src/Utils/sockets.cpp
- src/Utils/sockets.h
**Adds a `ClientSocket : public WebSocket` class to correctly connect to proxy web socket.**
Fixes an issue when connecting two emulator instances in out-of-place debugging, where the following error was thrown:
```error
Binding socket to address failed: Address already in use
```
> 🐛 Fix emu to emu connection in out-of-place debugging

- src/Debug/debugger.cpp
- src/Debug/debugger.h
- src/Interpreter/instructions.cpp
- src/Interpreter/interpreter.cpp
This PR adds a debugger interrupt that allows the VM to send a snapshot before every instruction it executes. This is useful for time travelling debuggers because it allows taking snapshots without pausing the VM.
The interrupt currently has number 61 associated with it (can be changed of course), I just noticed there was an empty spot right after snapshot. With `6101` you can enable tracing mode basically and with `6100` you can disable it again.
The `DUMP!` message printed before every snapshot is also removed, I did this to make it easier to add snapshot data to an existing line for example `SNAPSHOT {"pc": ...` which is the format used for this new interrupt. This format makes it easy to identify async snapshots. I just hope that `DUMP!` is not used by the plugin. The `DUMP!` message …
> Add async snapshot interrupt

- src/WARDuino/CallbackHandler.h
Tested with gcc (GCC) 13.2.1 20230801.
Fixed error was:
error: ‘uint32_t’ does not name a type
note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
> Fix build by adding missing cstdint include

- src/Primitives/arduino.cpp
**💥 Breaking Changes to Arduino primitives interface**
Removes the following primitives:
- `chip_ledc_setup`
- `chip_ledc_attach_pin`
Adds the following primitives:
- `chip_ledc_attach`
supported version: `arduino-cli v0.35.3`
> 🚑 Migrate to Arduino esp32 v3

- src/Debug/debugger.cpp
- src/Debug/debugger.h
- src/Interpreter/instructions.cpp
- src/Interpreter/interpreter.cpp
- src/Memory/mem.cpp
- src/Primitives/arduino.cpp
- src/Primitives/emulated.cpp
- src/Primitives/idf.cpp
- src/Primitives/primitives.h
- src/Primitives/zephyr.cpp
- src/Utils/sockets.cpp
- src/Utils/sockets.h
- src/WARDuino/CallbackHandler.cpp
(as an added bonus, also removed some CLion warnings...)
> 🚨 Refactorio #0: Fix all compiler warnings ♻️

- src/Debug/debugger.cpp
- src/Debug/debugger.h
- src/Interpreter/instructions.cpp
Adds the primitive mocking debugging interrupts that make it possible to set the return value for a primitive with one argument. Mocked primitives are also visible in the snapshots so that restoring a snapshot from the past also removes any primitives mocked using future values.
> ✨ Primitive mocking

- src/Primitives/arduino.cpp
- src/Primitives/emulated.cpp
- src/Primitives/idf.cpp
- src/Primitives/zephyr.cpp
- tests/unit/shared/serialisation.h
Very minor fixes that are useful when using a newer zephyr version or when wanting to use the DEBUG flag on the emulator.
Also fixes the unit tests not compiling on ubuntu due to a missing `cstdint` include.
> Fix DEBUG mode, include in zephyr primitives and typo

- .github/workflows/compile.yml
The Ubuntu 20.04 action is failing since Ubuntu 20.04 has been deprecated, this PR removes it from the list of operating systems.
[more info](https://github.com/actions/runner-images/issues/11101)
> CI: Remove Ubuntu 20.04

- src/Interpreter/instructions.cpp
- src/Interpreter/interpreter.cpp
- src/WARDuino/WARDuino.cpp
On some programs, the vm can run into an error like this `Unsigned LEB at byte 0x12800b011 overflow`. This overflow occurs when reading table indexes on the `call_indirect` function. It occurs because the table index in WARDuino can at most consist of 7 or 1 bits (the maximum amount of bit differs in two parts of the vm). In the wasm specification however, the table index is specified to be a u32. You would expect this error to only occur on modules using multiple tables but as it turns out this also happens on rust binaries that use just a single table. The reason for this is that the rust compiler can sometimes use a 5 byte table index `0x80 0x80 0x80 0x80 0x00` to encode table index 0 as described in [this](https://blog.rust-lang.org/2024/09/24/webassembly-targets-change-in-default-targ …
> Fix tableidx overflow on call_indirect

- src/Debug/debugger.cpp
Step over until now assumed that there were always 2 or 3 bytes of data associated with the `call` and `call_indirect` instructions. When working with larger programs however (or if the compiler uses a longer LEB representation than usual, which is allowed) this fixed byte count doesn't work anymore. Consequently, this PR makes step over actually read the LEB data instead of assuming it's always 1 byte.
> Fix stepOver using hardcoded immediate sizes

- src/Debug/debugger.cpp
This PR makes breakpoint AT messages create an automatic checkpoint.
This also means that step over will now result in a checkpoint telling the debugger how many instructions it stepped over.
> fix: make a checkpoint when hitting a breakpoint

- src/Primitives/emulated.cpp
This PR makes the emulator print the current pin state for digital writes to stdout.
Example:
```
EMU: chip_digital_write(12,0) 
EMU: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
EMU: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
EMU: chip_digital_write(13,1) 
EMU: 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 
EMU: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
```
> Print emulator pin state after chip_digital_write

- src/Primitives/emulated.cpp
The microseconds should be divided by 1000 to get the number of milliseconds.
> Fix millis on the emulator incorrectly converting the microseconds

- src/Primitives/emulated.cpp
Adds basic dummy primitives, this makes it possible to run Open Bot Brain programs on the emulator even though they don't control a physical robot. This is useful for testing purposes.
> Add dummy Open Bot Brain primitives
